#!/usr/bin/with-contenv bash
cd /
UMASK_SET=${UMASK_SET:-022}
umask "$UMASK_SET"

export SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(16))")


DB=/config/data.sqlite
if [ ! -f "$DB" ]; then
    s6-setuidgid abc python3 manage.py recreate_db
fi


exec \
	s6-setuidgid abc gunicorn \
    --bind unix:/tmp/gunicorn.sock \
    manage:app