#!/usr/bin/with-contenv bash
cd /
UMASK_SET=${UMASK_SET:-022}
umask "$UMASK_SET"

export SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(16))")

exec \
	s6-setuidgid abc uvicorn \
    --uds /tmp/gunicorn.sock \
    api.main:app