#!/usr/bin/with-contenv bash
cd /
#Stage a db migration
s6-setuidgid abc \
    alembic revision --autogenerate -m "automated db upgrade"
#Execute db migration
s6-setuidgid abc \
    alembic upgrade head