#!/usr/bin/with-contenv bash
cd /
#Stage a db migration
# s6-setuidgid abc \
#     sqlite3 /config/data.sqlite "DROP TABLE IF EXISTS alembic_version;"
s6-setuidgid abc \
    alembic revision --autogenerate -m "automated db upgrade"
#Execute db migration
s6-setuidgid abc \
    alembic upgrade head