#!/usr/bin/with-contenv bash
cd /
#Stage a db migration
# s6-setuidgid abc \
#     sqlite3 /config/data.sqlite "DROP TABLE IF EXISTS alembic_version;"
# Make sure versions folder exists
s6-setuidgid abc \
    mkdir -p /alembic/versions
# Prepare db migration
s6-setuidgid abc \
    alembic revision --autogenerate -m "automated db upgrade"
#Execute db migration
s6-setuidgid abc \
    alembic upgrade head
#Delete Alembic Versions Folder
# s6-setuidgid abc \
#     rm -rf /alembic/versions
